@startuml
'https://plantuml.com/class-diagram

skinparam groupInheritance 2

class Recipe {
    Guid Id
    string Name
    string ImageUrl
    string Description
    TimeSpan PreparationTime
    DateTime CreatedAt
    DateTime UpdatedAt
}

class Cook {
    Guid Id
    string UserName
    string FullName
    string ImageUrl
    DateTime CreatedAt
}

class Credential {
    string Email
    string EncryptedPassword
    DateTime UpdatedAt
}

class Ingredient {
    string Name
    string Description
    decimal Quantity
}

enum Unit {
    Milliliter,
    Deciliter,
    Liter,
    Milligram,
    Gram,
    Kilogram,
    Teaspoon,
    Tablespoon,
    FluidOunce,
    Cup,
    Pint,
    Quart,
    Gallon,
    Pound,
    Ounce
}

class PreparationStep {
    int Order
    string Description
}

enum Category {
    Appetizer
    MainCourse
    Dessert
}

class Reviewer {
    string UserName
    string FullName
    string ImageUrl
}

class Follower {
    string UserName
    string FullName
    string ImageUrl
}

class Liker {
    string UserName
    string FullName
    string ImageUrl
}

abstract class Review {
    Guid ReviewerId
    string Comment
    int Rating
    DateTime CreatedAt
}

class CookReview {
}

class RecipeReview {
}

Review <|-- CookReview
Review <|-- RecipeReview

Cook --> "*" Recipe
Cook -- Credential
Cook --> "*" CookReview
Cook --> "*" Follower

Recipe --> "*" Ingredient
Recipe --> "*" PreparationStep
Recipe --> "*" Category
Recipe --> "*" RecipeReview
Recipe --> "*" Liker

Ingredient -- Unit

Review -> Reviewer

@enduml